name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.9

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup conda conda.
        uses: conda-incubator/setup-miniconda@v3
        with:
          conda-channels: conda-forge,bioconda
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          # Install a specific version of uv and enable caching.
          version: "0.5.16"
          enable-cache: true

      - name: Set up Python
        run: uv python install ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests
        run: pytest

      - name: Check style with ruff
        run: flake8 .
